---
title: "Compare Scenarios NGFS"
date: "`r format(Sys.Date())`"
output:
  pdf_document:
    toc: yes
    number_sections: yes
    toc_depth: 6
    keep_tex: false
    template: csN_latex_template.tex
    includes: 
      in_header: csN_pdf_header_include.tex
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 6
    number_sections: yes
geometry: "a4paper,landscape,left=0.5cm,right=0.5cm,top=0.5cm,bottom=0.5cm,footnotesep=0.0cm,footskip=0.1cm"
params:
  snapshot: ""
  cfgScen: null
  cfgDefault: null
  mifHist: ""
  yearsScen: !r c(seq(2005, 2060, 5), seq(2070, 2100, 10))
  yearsHist: !r c(seq(1960, 2020, 1), seq(2025, 2100, 5))
  yearsBarPlot: !r c(2010, 2030, 2050, 2100)
  yearRef: 2020
  reg: null
  sections: "all"
  userSectionPath: null
  mainReg: "World"
  figWidth: 15 
  figHeight: 10
  warning: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  error = TRUE,
  message = FALSE,
  warning = params$warning,
  fig.width = params$figWidth,
  fig.height = params$figHeight)
```


```{r fix interactive plot size}
# Hack to use the same fig.width and fig.height as described in previous chunk
# for chunks in RStudio Notebook mode.
if (interactive()) {
  insertExprAtStartOfFun <- function(fun, funName, env, expr) {
    body(env[[funName]]) <- call("{", expr, body(fun))
  }
  fn <- ".rs.setNotebookGraphicsOption"
  envToolsRstudio <- as.environment("tools:rstudio")
  if (!exists(".old.rs.setNotebookGraphicsOption"))
    old.rs.setNotebookGraphicsOption <- envToolsRstudio[[fn]]
  insertExprAtStartOfFun(
    old.rs.setNotebookGraphicsOption,
    fn,
    envToolsRstudio,
    rlang::expr({
      width <- !!knitr::opts_chunk$get()$fig.width
      height <- !!knitr::opts_chunk$get()$fig.height
      units <- "in"
    })
  )
}
```


```{r libraries, include=FALSE}
# kableExtra must not be loaded before the call of library(kableExtra) below,
# as its .onLoad() function must be called to tell knitr about add necessary
# LaTeX libraries needed for tables.
# If the following line is not included, successive calls to compareScenarios2()
# may cause "Undefined control sequence" errors in LaTeX.
try(unloadNamespace("kableExtra"), silent = TRUE)

library(gridExtra)
options(tidyverse.quiet = TRUE)
library(tidyverse)
library(kableExtra)
library(quitte)
library(mip)
# NGFS specific
library(vroom)
source("C://Users/pascalwe/Code/NGFS/remind2/R/plotsNGFS.R")
```


```{r read config files}
if (!is.null(params$cfgScen)) {
  loadCfg <- function(path) {
    env <- new.env()
    load(path, envir = env)
    return(env$cfg)
  }
  tibble(path = unname(params$cfgScen)) %>%
    rowid_to_column("fileid") %>%
    mutate(cfg = map(path, loadCfg)) %>%
    unnest(cfg) %>%
    mutate(
      name = names(cfg),
      value = unname(cfg),
      cfg = NULL) ->
    cfgs
  cfgs %>%
    filter(name == "gms") %>%
    unnest(value) %>%
    mutate(name = names(value)) ->
    cfgGms
  cfgs %>%
    filter(name != "gms") ->
    cfgTopLevel
  rm(cfgs)
}
if (!is.null(params$cfgDefault)) {
  env <- new.env()
  source(params$cfgDefault, local = env, echo = FALSE)
  cfgDefault <- env$cfg
}
```


```{r read scenario mifs}
# decide which models should be part of the comparison
models_p2 <- c("GCAM5.3_NGFS", "MESSAGEix-GLOBIOM 1.1", "REMIND-MAgPIE 2.1-4.2")
models_p3 <- c("GCAM 5.3+ NGFS", "MESSAGEix-GLOBIOM 1.1-M-R12", "REMIND-MAgPIE 3.0-4.4")


# Read NGFS snapshot and transform into quitte (TODO: should be given as one argument to function)
snapshot_regi <- paste0(params$snapshot, "/output/snapshot_all_regions.csv")
snapshot_p2 <- "C:/Users/pascalwe/Data/NGFS/phase2/1624888306124-NGFS_Scenario_Data_IAM_outputs_V2.2.csv"

# inserted from Jeromes script
tmp <- vroom(snapshot_regi)
data_p3 <- tmp[, c("Model", "Scenario", "Region", "Variable", "Unit", paste(c(1995:2019, seq(2020,2100,5))))] %>%
  rename(model=Model, scenario=Scenario, region=Region, variable=Variable, unit=Unit) %>%
  pivot_longer(names_to="period", values_to="value", c(-model, -scenario, -region, -variable, -unit)) %>%
  mutate(period = as.numeric(period)) %>%
  filter(model %in% models_p3)

tmp_p2 <- vroom(snapshot_p2)
data_p2 <- tmp_p2[, c("Model", "Scenario", "Region", "Variable", "Unit", paste(c(1990, 1995, 2000:2019, seq(2020,2100,5))))] %>%
  rename(model=Model, scenario=Scenario, region=Region, variable=Variable, unit=Unit) %>%
  pivot_longer(names_to="period", values_to="value", c(-model, -scenario, -region, -variable, -unit)) %>%
  mutate(period = as.numeric(period)) %>%
  filter(model %in% models_p2)

rm(tmp, tmp_p2)

# rename models except if only section 02 is present
if (params$sections != 2) {
  models_p2_new <- c("GCAM_Ph2", "MSGE_Ph2", "RMND_Ph2")
  models_p3_new <- c("GCAM_Ph3", "MSGE_Ph3", "RMND_Ph3")
  
  for (m in 1:3) {
    data_p2[data_p2$model == models_p2[m], "model"]    <- models_p2_new[m]
    data_p3[data_p3$model == models_p3[m], "model"]    <- models_p3_new[m]
  }
}
```

```{r define scenario colors}
# Get colors of scenarios to be used, e.g., in the info sections.
# They will coincide with the colors of the scenarios in line plots.
# TODO: Adapt to NGFS
# scenarioColors <- plotstyle(fileReference$newScenarioName)
# lightenColor <- function(clr, by) {
#   colRGB <- colorRamp(c(clr, "white"))(by)
#   rgb(colRGB[1], colRGB[2], colRGB[3], maxColorValue = 255)
# }
# bkgndColors <- sapply(scenarioColors, lightenColor, by = 0.5)
```


```{r read historical mif}
params$mifHist %>%
  read.quitte(factors = TRUE) ->
  data_hist
```


```{r preprocess}
# Filter years and NA.
data_p3 %>%
  filter(period %in% params$yearsScen, !is.na(value)) ->
  data_p3

data_p2 %>%
  filter(period %in% params$yearsScen, !is.na(value)) ->
  data_p2

data_hist %>%
  filter(period %in% params$yearsHist, !is.na(value)) ->
  data_hist

# quick region harmonization
# same from start: IND, JPN, US?, CHN?, EU?, R5/10? 
# -> historical data need harmonization from REMIND style to NGFS style
levels(data_hist$region) <- c(levels(data_hist$region), "EU", "CHN", "RUS")
data_hist[data_hist$region == "EUR", "region"] <- "EU"   # not perfect match
data_hist[data_hist$region == "CHA", "region"] <- "CHN"  # not perfect match
data_hist[data_hist$region == "REF", "region"] <- "RUS"  # not perfect match at all

# harmonize scenario names with phase 2 data
data_p2[grep("Below 2", data_p2$scenario),"scenario"]  <- "o_2c"
data_p2[data_p2$scenario == "Net Zero 2050", "scenario"]    <- "o_1p5c"
data_p2[data_p2$scenario == "Current Policies", "scenario"] <- "h_cpol"
data_p2[data_p2$scenario == "Nationally Determined Contributions (NDCs)", "scenario"] <- "h_ndc"
data_p2[data_p2$scenario == "Delayed transition", "scenario"] <- "d_delfrag"
data_p2[data_p2$scenario == "Divergent Net Zero", "scenario"] <- "d_rap"



# Combine into one data frame and remove old.
data_p3 <- bind_rows(data_p3, data_p2)
data <- bind_rows(data_p3, data_hist)
rm(data_p2, data_p3, data_hist)

# In the variable names, replace |+|, |++|, |+++|, ... by |.
data %>%
  mutate(
    varplus = as.character(variable),
    variable = remind2::deletePlus(variable)) ->
  data

# Filter regions.
if (!is.null(params$reg)) {
  data %>%
    filter(region %in% params$reg) ->
    data
}

# GDP available in $2005 and $2010 in REMIND, remove 2005 (also might remove historical data!)
data <- filter(data, !(variable == "GDP|PPP" & unit == "billion US$2005/yr"))
# remove EDGE-scenarios
data <- data[grep("EDGE", data$model, invert=T), ]

# sort scenarios in a more logical order
data$scenario <- factor(as.character(data$scenario),
                        levels=c("h_cpol", "h_ndc", "o_1p5c", "o_2c", "d_delfrag", "d_rap", "historical"))


# more data processing? Removing some projections, like Innopath data?
```


```{r Corrections}
# TODO: Should not be done in compareScenarios.

# Change unit million US$2005/yr to billion US$2005/yr.
# Relevant for ARIADNE historical EUR GDP|PPP.
bind_rows(
  data %>% filter(!unit %in% c("million US$2005/yr")),
  data %>%
    filter(unit == "million US$2005/yr") %>%
    mutate(
      unit = "billion US$2005/yr",
      value = value / 1000)) ->
  data
```


```{r reference models for historical}
# Sometimes it is necessary to choose a single model for the historical data,
# e.g., calculating per capita variables. These reference models are defined here.
histRefModel <- c(
  "Population" = "WDI",
  "GDP|PPP pCap" = "James_IMF")
```


```{r prepare IEA net-zero data}
# prepare IEA Data in case it is needed
if (any(c(5,6,7) %in% params$sections)) {
  u_ngfs_scenario <- c("Net Zero 2050")  # TODO: this should be solved differently, either hardcode or make truly flexible
  tmstmp <- Sys.Date()
  
  # use "world" file from snapshot, do data preparation as Jerome did
  snapshot_world_p3 <- paste0(params$snapshot, "/output/snapshot_world.csv")
  data_p3 <- read.csv(snapshot_world_p3) %>%
    rename(model=Model, scenario=Scenario, region=Region, variable=Variable, unit=Unit) %>%
    pivot_longer(names_to = "period", values_to = "value", cols = c(-"model", -"scenario", -"region", -"variable", -"unit")) %>%
    mutate(period = as.numeric(substr(period,start = 2,stop = 5))) %>%
    filter(!is.na(value))

  data_ngfs_world_p3 <- data_p3 %>% filter(region=="World", period %in% seq(2005,2100,5), scenario=="o_1p5c")
  data_ngfs_world_p3[data_ngfs_world_p3$scenario == "o_1p5c", "scenario"] <- "Net Zero 2050"
  data_ngfs_world_p3$model <- as.character(data_ngfs_world_p3$model)

  data_ngfs_world_p3 <- data_ngfs_world_p3 %>%
    filter(!grepl("*IntegratedPhysicalDamages", model)) %>%
    mutate(model = ifelse(grepl("GCAM", model),      "GCAM", model)) %>%
    mutate(model = ifelse(grepl("MESSAGE", model),   "MESSAGEix-GLOBIOM", model)) %>%
    mutate(model = ifelse(grepl("REMIND", model),    "REMIND-MAgPIE", model))
  
  
  # TODO: this could be replaced with new data/generic phase 2 data, use data from historical.mif as imported above
  b <- load(file="C:/Users/pascalwe/Code/NGFS/iea_netzero_2021/data/ngfs_data_world_v2p2.RData")
  # Load SR 15, AR6 data
  a <- load(file="C:/Users/pascalwe/Code/NGFS/iea_netzero_2021/data/IPCC_data_sr15_ar6.RData")
  #reduce size...
  data_ar6 <- data_ar6 %>% filter(region=="World", period %in% seq(2005,2100,5))
  data_iea_nz <- read.quitte("C:/Users/pascalwe/Code/NGFS/iea_netzero_2021/data/historical_IEA_nz2050.csv")
  data_iea_nz$scenario <- "NZE2050"
  # divide IEA PE Nuclear by 3, as they scale it up in their reporting
  data_iea_nz[data_iea_nz$variable == "Primary Energy|Nuclear", "value"] = 
    data_iea_nz[data_iea_nz$variable == "Primary Energy|Nuclear", "value"] / 3
  # manually add and rename CO2 energy emissions from historical.mif
  data_iea_nz <- bind_rows(data_iea_nz, data %>% 
                             filter(model=="IEA WEO 2021 Net2050", variable=="Emi|CO2|Energy") %>%
                             mutate(variable="Emissions|CO2|Energy", scenario="NZE2050"))
}
```


```{r quitte}
data <- as.quitte(data)
```


```{r global variables}
# Set global variables for use in plotting.
options(mip.mainReg = params$mainReg)
options(mip.yearsBarPlot = params$yearsBarPlot)
options(mip.histRefModel = histRefModel)

# Reference year for Kaya decomposition is params$yearRef or the first available year therafter.
options(kaya.refYear = min(params$yearsScen[params$yearsScen >= params$yearRef]))
```



```{r sectionPaths}
dir() %>%
  str_match("^csN_([0-9]+).+\\.Rmd$") ->
  matches
tibble(
  files = matches[, 1],
  nums = as.numeric(matches[, 2])) %>%
  drop_na() %>%
  arrange(files) ->
  availableSections
if (length(params$sections) == 1 && params$sections == "all") {
  sectionPaths <- availableSections$files
} else if (is.numeric(params$sections)) {
  tibble(nums = params$sections) %>%
    left_join(availableSections, by = "nums") %>%
    drop_na() %>%
    pull(files) ->
    sectionPaths
} else {
  if (length(params$sections) > 0) {
    sectionPaths <- paste0("csN_", params$sections, ".Rmd")
  } else {
    sectionPaths <- character(0)
  }
}
```


```{r prepare mark}
# CLICK "RUN ALL CHUNKS ABOVE" HERE TO PREPARE THE ENVIRONMENT
```


```{r include sections, child = sectionPaths}

```


```{r include user section, child = params$userSectionPath}

```
