# Macro


## Population
### by Model
```{r Population by Model}
var  = "Population"
showLinePlots_NGFS(data, var, iam = "REMIND")
showLinePlots_NGFS(data, var, iam = "GCAM")
showLinePlots_NGFS(data, var, iam = "MESSAGE")
```

### by Scenario
```{r Population by Scenario}
showLinePlots_NGFS(data, var, scen = "d_delfrag")
showLinePlots_NGFS(data, var, scen = "d_rap")
showLinePlots_NGFS(data, var, scen = "h_cpol")
showLinePlots_NGFS(data, var, scen = "h_ndc")
showLinePlots_NGFS(data, var, scen = "o_1p5c")
showLinePlots_NGFS(data, var, scen = "o_2c")
```

## GDP - PPP
### by Model
```{r GDP-PPP by Model}
var = "GDP|PPP"


showLinePlots_NGFS(data, var, iam = "REMIND", show_hist = F)
showLinePlots_NGFS(data, var, iam = "GCAM", show_hist = F)
```

### by Scenario
```{r GDP-PPP by Scenario}
showLinePlots_NGFS(data, var, scen = "d_delfrag", show_hist = F)
showLinePlots_NGFS(data, var, scen = "d_rap", show_hist = F)
showLinePlots_NGFS(data, var, scen = "h_cpol", show_hist = F)
showLinePlots_NGFS(data, var, scen = "h_ndc", show_hist = F)
showLinePlots_NGFS(data, var, scen = "o_1p5c", show_hist = F)
showLinePlots_NGFS(data, var, scen = "o_2c", show_hist = F)
```
