## File References


```{r results='asis'}
cat(
  "\"Snapshot\" in use is taken from ", 
  str_replace_all(params$snapshot, fixed("\\"), "/"),
  ".\n\n")
cat(
  "\"Historical\" data is taken from ", 
  str_replace_all(params$mifHist, fixed("\\"), "/"),
  ".\n\n")

# Scenario availability (TODO: better as table)
for (model in models_p3_new) {
  cat(model, " contains data for the following scenarios:\n\n ")
  for (s in unique(data[data$model == model, "scenario"])) {
    cat(paste0(s, "\n"))
  }
  cat("\n")
}

for (model in models_p2_new) {
  cat(model, " contains data for the following scenarios:\n\n ")
  for (s in unique(data[data$model == model, "scenario"])) {
    cat(paste0(s, "\n"))
  }
  cat("\n")
}
```


```{r results='asis'}
# If paths to config files are provided in the parameter cfgScen, their
# content is written to the objects cfgGms and cfgTopLevel in csN_main.Rmd. Here
# and in the next chunks, relevant parts of these configs are displayed.

# Show cfgTopLevel$description (originally cfg$description).
if (exists("cfgTopLevel") && !is.null(cfgTopLevel)) {

  cat("## Descriptions\n\n")

  for (i in 1:max(fileReference$fileid)) {
    cat("### ", as.character(fileReference$newScenarioName[i]), "\n\n")

    cfgTopLevel %>%
      filter(fileid == i, name == "description") %>%
      pull(value) %>%
      pluck(1) ->
      description
    cat(description, "\n\n")
  }
}
```

\newpage
