#' Read in GDX, GAINS2025 emission factors and baseyear emissions and
#' calculate air pollution emissions, used in convGDX2MIF.R for
#' the reporting
#'
#' @param gdx a GDX as created by readGDX, or the file name of a gdx
#' @param output a magpie object containing all needed variables generated by other report*.R functions
#' @param regionSubsetList a list containing regions to create report variables region
#' aggregations. If NULL (default value) only the global region aggregation "GLO" will
#' be created.
#' @param t temporal resolution of the reporting, default:
#' t=c(seq(2005,2060,5),seq(2070,2110,10),2130,2150)
#' @param extraData path to extra data files to be used in the reporting
#' @param addTmpTotal choose if temporary totals are computed (default = FALSE)
#'
#' @author Laurin Köhler-Schindler
#' @examples
#' \dontrun{
#' reportAirPollutantEmissions(gdx)
#' }
#' @export
#' @importFrom gdx readGDX
#'

reportAirPollutantEmissions <- function(gdx, output = NULL, regionSubsetList = NULL,
                                        t = c(seq(2005, 2060, 5), seq(2070, 2110, 10), 2130, 2150),
                                        extraData = NULL, addTmpTotal = FALSE) {
  # 1. LOAD REMIND ACTIVITIES --------------------------------------------------

  # air pollutant emissions calculation requires information from other reporting functions
  if (is.null(output)) {
    message("reportAirPollutantEmissions executes reportMacroEconomy ", appendLF = FALSE)
    output <- mbind(output, reportMacroEconomy(gdx, regionSubsetList = regionSubsetList, t = t))
    message("- reportPE ", appendLF = FALSE)
    output <- mbind(output, reportPE(gdx, regionSubsetList = regionSubsetList, t = t))
    message("- reportSE ", appendLF = FALSE)
    output <- mbind(output, reportSE(gdx, regionSubsetList = regionSubsetList, t = t))
    message("- reportFE ", appendLF = FALSE)
    output <- mbind(output, reportFE(gdx, regionSubsetList = regionSubsetList, t = t))
  }

  # Drop intermediate regional aggregations
  if (!is.null(regionSubsetList)) {
    output <- output[names(regionSubsetList), , , invert = TRUE]
  }

  # 2. LOAD GAINS EMISSION FACTORS AND BASEYEAR EMISSIONS ----------------------

  # 2.1. Derive AP scenario, source, and ssp for air pollutant emissions calculation
  ap_scenario <- readGDX(gdx, "cm_APscen")
  cm_APssp <- readGDX(gdx, "cm_APssp")
  cm_GDPpopScen <- readGDX(gdx, "cm_GDPpopScen")
  ap_source <- as.numeric(readGDX(gdx, "cm_APsource"))
  # get AP ssp
  if (ap_scenario == "MTFR" || ap_scenario == "SMIPVLLO") {
    # MTFR and SMIPVLLO are not differentiated by SSP, so set to ap_scenario
    ap_ssp <- ap_scenario
  } else if (ap_scenario == "CLE" || ap_scenario == "SLE" || ap_scenario == "SMIPbySSP") {
    # CLE, SLE and SMIPbySSP are differentiated by SSP, but SSP4 is not available for SMIPbySSP
    if (ap_scenario == "SMIPbySSP" && ((cm_APssp == "SSP4") || (cm_APssp == "FROMGDPSSP" && cm_GDPpopScen == "SSP4"))) {
      stop(paste0("cm_APssp 'SSP4' is not available for SMIPbySSP. Please select another SSP."))
    }
    # Determine ap_ssp based on cm_APscen and cm_APssp setting
    if (cm_APssp == "FROMGDPSSP") {
      ap_ssp <- cm_GDPpopScen
    } else if (cm_APssp %in% c("SSP1", "SSP2", "SSP3", "SSP4", "SSP5")) {
      ap_ssp <- cm_APssp
    } else {
      stop(paste0("cm_APssp '", cm_APssp, "' is not supported by exoGAINS2025. Please select one of the following: FROMGDPSSP, SSP1-5"))
    }
  } else {
    stop(paste0("cm_APscen '", ap_scenario, "' is not supported by exoGAINS2025. Please select one of the following: CLE, SLE, MTFR, SMIPbySSP, SMIPVLLO"))
  }
  # 2.2. Load and select AP data based on ap_scenario, ap_ssp, and ap_source
  # Select the source
  if (ap_source == 1) {
    # CEDS2025 emissions (mapped to GAINS sectors) are used as baseyear (2020) emissions
    file_name_emi2020 <- "emi2020_sectGAINS_sourceCEDS"
    file_name_emifacs <- "emifacs_sectGAINS_sourceCEDS"
  } else if (ap_source == 2) {
    # GAINS2025 emissions (from baseline scenario) are used as baseyear (2020) emissions
    file_name_emi2020 <- "emi2020_sectGAINS_sourceGAINS"
    file_name_emifacs <- "emifacs_sectGAINS_sourceGAINS"
  } else {
    stop(paste0("Unknown source of AP baseyear emissions. cm_APsource: ", ap_source))
  }

  # Load the data from RSE server or from extraData folder
  file_name_apmagpie <- "AirPollutantsMAgPIE"

  if (is.null(extraData)) {
    # download auxiliary file from RSE server
    regionHash <- digest::digest(sort(readGDX(gdx, "all_regi")), "xxhash32")
    # baseyear (2020) emissions
    file_name_emi2020_regi <- switch(regionHash,
      "69585993" = paste0(file_name_emi2020, "_h12.cs4r"),
      "8c818b67" = paste0(file_name_emi2020, "_eu21.cs4r")
    )
    if (is.null(file_name_emi2020_regi)) {
      stop(paste0("No file '", file_name_emi2020, "' found for regions in .gdx file."))
    }
    file_emi2020 <- downloadAuxiliaryFile(file_name_emi2020_regi)
    emi2020 <- read.magpie(file_emi2020)
    # emission factors
    file_name_emifacs_regi <- switch(regionHash,
      "69585993" = paste0(file_name_emifacs, "_h12.cs4r"),
      "8c818b67" = paste0(file_name_emifacs, "_eu21.cs4r")
    )
    if (is.null(file_name_emifacs_regi)) {
      stop(paste0("No file '", file_name_emifacs, "' found for regions in .gdx file."))
    }
    file_emifacs <- downloadAuxiliaryFile(file_name_emifacs_regi)
    emifacs <- read.magpie(file_emifacs)
    # air pollutant emissions from MAgPIE
    file_name_apmagpie_regi <- switch(regionHash,
      "69585993" = paste0(file_name_apmagpie, "_H12.cs4r"),
      "8c818b67" = paste0(file_name_apmagpie, "_21_EU11.cs4r")
    )
    if (is.null(file_name_apmagpie_regi)) {
      stop(paste0("No file '", file_name_apmagpie, "' found for regions in .gdx file."))
    }
    file_apmagpie <- downloadAuxiliaryFile(file_name_apmagpie_regi)
    APMagpie <- read.magpie(file_apmagpie)
  } else {
    # check that files exist
    if (!file.exists(file.path(extraData, paste0(file_name_emi2020, ".cs4r")))) {
      stop(paste0("Auxiliary file '", file_name_emi2020, ".cs4r' not found."))
    } else if (!file.exists(file.path(extraData, paste0(file_name_emifacs, ".cs4r")))) {
      stop(paste0("Auxiliary file '", file_name_emifacs, ".cs4r' not found."))
    } else if (!file.exists(file.path(extraData, paste0(file_name_apmagpie, ".cs4r")))) {
      # For backwards compatibility: for version <= 3.6.0 this file does not exists, therefore dont stop
      # With the next release 3.7.0 the following line should be commented in again.
      #stop(paste0("Auxiliary file '", file_name_apmagpie, ".cs4r' not found."))
      message("No land use air pollutants loaded since ", file.path(extraData, paste0(file_name_apmagpie, ".cs4r")), " is missing")
    }

    # read files
    emi2020  <- read.magpie(file.path(extraData, paste0(file_name_emi2020, ".cs4r")))
    emifacs  <- read.magpie(file.path(extraData, paste0(file_name_emifacs, ".cs4r")))
    # This if statement can be removed with release 3.7.0
    if (file.exists(file.path(extraData, paste0(file_name_apmagpie, ".cs4r")))) {
      APMagpie <- read.magpie(file.path(extraData, paste0(file_name_apmagpie,".cs4r")))
    }
  }

  # Set dim names
  getSets(emi2020) <- c("region", "year", "sector", "species")
  getSets(emifacs) <- c("region", "year", "ssp", "scenario", "sector", "species")

  # Subset the chosen scenario and SSP
  emifacs <- emifacs[, , list(ssp = ap_ssp, scenario = ap_scenario)]
  emifacs <- collapseDim(emifacs, dim = c("ssp", "scenario"))

  # Check if regional resolution matches
  all_regi <- readGDX(gdx, "all_regi")
  if (length(setdiff(all_regi, getItems(emi2020, dim = 1))) != 0 ||
    length(setdiff(getItems(emi2020, dim = 1), all_regi)) != 0
  ) {
    stop(paste0("Regional resolution in '", file_name_emi2020, ".cs4r' and gdx do not match."))
  } else if (length(setdiff(all_regi, getItems(emifacs, dim = 1))) != 0 ||
    length(setdiff(getItems(emifacs, dim = 1), all_regi)) != 0
  ) {
    stop(paste0("Regional resolution in '", file_name_emifacs, ".cs4r' and gdx do not match."))
  }

  # 3. CALCULATE AIR POLLUTANT EMISSIONS FOR GAINS SECTORS ---------------------

  emis_projected_AP <- exoGAINS2025AirPollutants(
    remind_output = output,
    gains_emifacs = emifacs,
    baseyear_emis_2020 = emi2020
  )

  # 4. REPORT AIR POLLUTANT EMISSIONS FOR GAINS SECTORS ------------------------

  airpollutants <- c("BC", "CO", "NH3", "NOx", "OC", "SO2", "VOC")

  # Get mapping from GAINS2025 sectors to REMIND reporting variables
  map_GAINS2REMIND <- toolGetMapping(type = "sectoral", name = "mappingGAINS2025toREMIND.csv", where = "remind2")

  # 4.1 REPORTING AT THE LEVEL OF GAINS SECTORS --------------------------------

  # Internal reporting function per pollutant
  generateAirPollutantEmissionsReporting <- function(pollutant, mapping = map_GAINS2REMIND, emissions = emis_projected_AP) {
    # Reduce to the pollutant
    AP_in <- collapseDim(emissions[, , pollutant], dim = 3.2)

    # Get REMIND variable names
    AP_mapping <- mapping %>%
      mutate("REMINDvariable" = paste0("Emi|", pollutant, "|", .data$REMINDreporting, " (Mt ", pollutant, "/yr)")) %>%
      select("GAINSsector", "REMINDvariable")

    # Rename GAINS sectors to REMIND variable names
    AP_out <- setNames(AP_in[, , AP_mapping$GAINSsector], as.character(AP_mapping$REMINDvariable))

    return(AP_out)
  }

  # Report each pollutant
  output_AP_unaggregated <- do.call("mbind", lapply(airpollutants, generateAirPollutantEmissionsReporting))
  getSets(output_AP_unaggregated)["d3.1"] <- "variable"

  # Add other region aggregations
  if (!is.null(regionSubsetList)) {
    output_AP_unaggregated <- mbind(output_AP_unaggregated, calc_regionSubset_sums(output_AP_unaggregated, regionSubsetList))
  }

  # 4.2 REPORTING OF SECTORAL AGGREGATIONS -------------------------------------

  # Internal helper function for aggregation
  sumAPchilds <- function(parent_name, childs_startWith, data, poll) {
    # All variable names in data (no subdimensions!)
    all_vars <- getItems(data, dim = 3)
    # Selected variable names based on childs_startWith
    selected_vars <- all_vars[startsWith(all_vars, paste0("Emi|", poll, "|", childs_startWith, "|+|"))]
    # Add aggregation to new parent variable
    extended_data <- mbind(
      data,
      setNames(
        dimSums(data[, , selected_vars], dim = 3),
        paste0("Emi|", poll, "|", parent_name, " (Mt ", poll, "/yr)")
      )
    )
    return(extended_data)
  }

  # Internal aggregation function per pollutant
  addAirPollutantEmissionsAggregation <- function(input = output_AP_unaggregated) {
    # Initialize output
    output <- input
    # Loop over all pollutants
    for (pollutant in airpollutants) {
      # Industrial Processes
      output <- sumAPchilds(
        parent_name = "Industrial Processes",
        childs_startWith = "Industrial Processes", data = output, poll = pollutant
      )
      # Waste
      output <- sumAPchilds(
        parent_name = "Waste",
        childs_startWith = "Waste", data = output, poll = pollutant
      )
      # Energy|Demand|Industry|+|Solids
      output <- sumAPchilds(
        parent_name = "Energy|Demand|Industry|+|Solids",
        childs_startWith = "Energy|Demand|Industry|Solids", data = output, poll = pollutant
      )
      # Energy|Demand|Industry|+|Liquids
      output <- sumAPchilds(
        parent_name = "Energy|Demand|Industry|+|Liquids",
        childs_startWith = "Energy|Demand|Industry|Liquids", data = output, poll = pollutant
      )
      # Energy|Demand|Industry
      output <- sumAPchilds(
        parent_name = "Energy|Demand|Industry",
        childs_startWith = "Energy|Demand|Industry", data = output, poll = pollutant
      )
      # Energy|Demand|Residential|Solids|+|Biomass
      output <- sumAPchilds(
        parent_name = "Energy|Demand|Residential|Solids|+|Biomass",
        childs_startWith = "Energy|Demand|Residential|Solids|Biomass", data = output, poll = pollutant
      )
      # Energy|Demand|Residential|+|Solids
      output <- sumAPchilds(
        parent_name = "Energy|Demand|Residential|+|Solids",
        childs_startWith = "Energy|Demand|Residential|Solids", data = output, poll = pollutant
      )
      # Energy|Demand|Residential|+|Liquids
      output <- sumAPchilds(
        parent_name = "Energy|Demand|Residential|+|Liquids",
        childs_startWith = "Energy|Demand|Residential|Liquids", data = output, poll = pollutant
      )
      # Energy|Demand|Residential
      output <- sumAPchilds(
        parent_name = "Energy|Demand|Residential",
        childs_startWith = "Energy|Demand|Residential", data = output, poll = pollutant
      )
      # Energy|Demand|Commercial|+|Solids
      output <- sumAPchilds(
        parent_name = "Energy|Demand|Commercial|+|Solids",
        childs_startWith = "Energy|Demand|Commercial|Solids", data = output, poll = pollutant
      )
      # Energy|Demand|Commercial
      output <- sumAPchilds(
        parent_name = "Energy|Demand|Commercial",
        childs_startWith = "Energy|Demand|Commercial", data = output, poll = pollutant
      )
      # Energy|Demand|Buildings
      output <- mbind(
        output,
        setNames(
          dimSums(output[, , c(
            paste0("Emi|", pollutant, "|Energy|Demand|Residential (Mt ", pollutant, "/yr)"),
            paste0("Emi|", pollutant, "|Energy|Demand|Commercial (Mt ", pollutant, "/yr)")
          )], dim = 3),
          paste0("Emi|", pollutant, "|Energy|Demand|Buildings (Mt ", pollutant, "/yr)")
        )
      )
      # Energy|Demand|Transport|Ground|+|Liquids
      output <- sumAPchilds(
        parent_name = "Energy|Demand|Transport|Ground|+|Liquids",
        childs_startWith = "Energy|Demand|Transport|Ground|Liquids", data = output, poll = pollutant
      )
      # Energy|Demand|Transport|Ground
      output <- sumAPchilds(
        parent_name = "Energy|Demand|Transport|Ground",
        childs_startWith = "Energy|Demand|Transport|Ground", data = output, poll = pollutant
      )

      # Energy|Supply|+|Extraction
      output <- sumAPchilds(
        parent_name = "Energy|Supply|+|Extraction",
        childs_startWith = "Energy|Supply|Extraction", data = output, poll = pollutant
      )
      # Energy|Supply|Electricity|+|Solids
      output <- sumAPchilds(
        parent_name = "Energy|Supply|Electricity|+|Solids",
        childs_startWith = "Energy|Supply|Electricity|Solids", data = output, poll = pollutant
      )
      # Energy|Supply|Electricity|+|Liquids
      output <- sumAPchilds(
        parent_name = "Energy|Supply|Electricity|+|Liquids",
        childs_startWith = "Energy|Supply|Electricity|Liquids", data = output, poll = pollutant
      )
      # Energy|Supply|+|Electricity
      output <- sumAPchilds(
        parent_name = "Energy|Supply|+|Electricity",
        childs_startWith = "Energy|Supply|Electricity", data = output, poll = pollutant
      )
      # Energy|Supply|+|Transformation
      output <- sumAPchilds(
        parent_name = "Energy|Supply|+|Transformation",
        childs_startWith = "Energy|Supply|Transformation", data = output, poll = pollutant
      )
      # Energy|Supply
      output <- sumAPchilds(
        parent_name = "Energy|Supply",
        childs_startWith = "Energy|Supply", data = output, poll = pollutant
      )
    }
    return(output)
  }

  # Add aggregates for each pollutant
  output_AP_aggregated <- addAirPollutantEmissionsAggregation(output_AP_unaggregated)


  # 5. REPORTING OF land use emissions provided by MAgPIE -------------------------------------

  # The if statement can be removed with release 3.7.0. It exists for backwards compatibility with releases <= 3.6.0
  # which do not include the MAgPIE airpollutant emissions
  if (! exists("APMagpie")) {
    output_AP_aggregated <- add_columns(output_AP_aggregated, addnm = paste0("Emi|", airpollutants, "|AFOLU (Mt ", airpollutants, "/yr)"), dim = 3.1, fill = 0)
  } else {

    # The structure of the air pollutant data from MAgPIE depend on whether it is
    # a standalone run (source: mcommons) or a coupled run (source: coupling script)
    cm_MAgPIE_Nash <- readGDX(gdx, "cm_MAgPIE_Nash") |> as.vector()

    if (cm_MAgPIE_Nash == 0) {
      # standalone mode
      getSets(APMagpie) <- c("region", "year", "ssp", "rcp", "variable")
      cm_LU_emi_scen <- suppressWarnings(readGDX(gdx, "cm_LU_emi_scen"))
      cm_rcp_scen <- suppressWarnings(readGDX(gdx, "cm_rcp_scen"))

      # Backwards compatibility: if the scenario information is not available in the gdx, use default values
      # Can be removed with release 3.7.0
      if (is.null(cm_LU_emi_scen)) cm_LU_emi_scen <- readGDX(gdx, "cm_GDPpopScen")
      if(is.null(cm_rcp_scen)) cm_rcp_scen <- "rcp45"

      # Subset the chosen scenario and SSP
      APMagpie <- APMagpie[, , list(ssp = cm_LU_emi_scen, rcp = cm_rcp_scen)]
      APMagpie <- collapseDim(APMagpie, dim = c("ssp", "rcp"))
    } else {
      # in coupled mode expect other dimensions (no ssp and rcp dimension)
      getSets(APMagpie) <- c("region", "year", "variable")
    }

    # Add sum across regions as global
    GLO <- dimSums(APMagpie, dim = 1)
    getItems(GLO, dim = 1) <- "GLO"
    APMagpie <- mbind(APMagpie, GLO)

    # Add other region aggregations
    if (!is.null(regionSubsetList)) {
      APMagpie <- mbind(APMagpie, calc_regionSubset_sums(APMagpie, regionSubsetList))
    }

    # "AFOLU|+|Agriculture" only exists for NH3 and NOx, but it is needed for the summation to "AFOLU". Thus, we add it as zero for all other species
    airpollutants_wo_NH3_NOx <- setdiff(airpollutants, c("NH3", "NOx"))
    zeroAgriculture <- new.magpie(cells_and_regions = getItems(APMagpie, dim = 1),
               years = getItems(APMagpie, dim = 2),
               names = paste0("Emi|", airpollutants_wo_NH3_NOx, "|AFOLU|+|Agriculture (Mt ", airpollutants_wo_NH3_NOx, "/yr)"),
               fill = 0)

    APMagpie <- mbind(APMagpie, zeroAgriculture)

    for (pollutant in airpollutants) {
      APMagpie <- mbind(
        APMagpie,
        setNames(
          dimSums(APMagpie[, , c(
            #paste0("Emi|", pollutant, "|AFOLU|Land|+|Peatland (Mt ", pollutant, "/yr)"),
            paste0("Emi|", pollutant, "|AFOLU|Land|+|Fires (Mt ", pollutant, "/yr)")
          )], dim = 3),
          paste0("Emi|", pollutant, "|AFOLU|+|Land (Mt ", pollutant, "/yr)")
        ),
        setNames(
          dimSums(APMagpie[, , c(
            paste0("Emi|", pollutant, "|AFOLU|+|Agriculture (Mt ", pollutant, "/yr)"),
            paste0("Emi|", pollutant, "|AFOLU|+|Agricultural Waste Burning (Mt ", pollutant, "/yr)"),
            #paste0("Emi|", pollutant, "|AFOLU|Land|+|Peatland (Mt ", pollutant, "/yr)"),
            paste0("Emi|", pollutant, "|AFOLU|Land|+|Fires (Mt ", pollutant, "/yr)")
          )], dim = 3),
          paste0("Emi|", pollutant, "|AFOLU (Mt ", pollutant, "/yr)")
        )
      )
    }

    output_AP_aggregated <- mbind(output_AP_aggregated, APMagpie[,t,])
    }

    # TEMPORARY SOLUTION TO GET TOTALS FOR reportEmiForClimateAssessment
    ## AP emissions from shipping and aviation can only be computed in
    ## reportExtraEmissions based on EDGE-T variables. Thus, they can
    ## currently not be handed to reportEmiForClimateAssessment which
    ## needs to run between iterations.
    ##
    ## Thus, we compute incomplete aggregate from available top level variabes
    ## "Energy|Demand|Industry", "Energy|Demand|Buildings",
    ## "Energy|Demand|Transport|Ground", "Energy|Supply", "Industrial Processes",
    ## "Product Use|Solvents", "Waste", and "AFOLU" to TOTAL
    if (addTmpTotal) {
      tmp_AP_total <- NULL
      for (pollutant in airpollutants) {
        tmp_AP_total <- mbind(tmp_AP_total, setNames(
          dimSums(output_AP_aggregated[, , c(
            paste0("Emi|", pollutant, "|Energy|Demand|Industry (Mt ", pollutant, "/yr)"),
            paste0("Emi|", pollutant, "|Energy|Demand|Buildings (Mt ", pollutant, "/yr)"),
            paste0("Emi|", pollutant, "|Energy|Demand|Transport|Ground (Mt ", pollutant, "/yr)"),
            paste0("Emi|", pollutant, "|Energy|Supply (Mt ", pollutant, "/yr)"),
            paste0("Emi|", pollutant, "|Industrial Processes (Mt ", pollutant, "/yr)"),
            paste0("Emi|", pollutant, "|Product Use|Solvents (Mt ", pollutant, "/yr)"),
            paste0("Emi|", pollutant, "|Waste (Mt ", pollutant, "/yr)"),
            paste0("Emi|", pollutant, "|AFOLU (Mt ", pollutant, "/yr)")
          )], dim = 3),
          paste0("Emi|", pollutant, " (Mt ", pollutant, "/yr)")
        ))
      }

      output_AP_aggregated <- mbind(output_AP_aggregated, tmp_AP_total)
  }

  return(output_AP_aggregated)
}
